[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGON_API_KEY}", chain = "polygon" }
