[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_solc = true
optimizer = true
optimizer_runs = 200

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "params_first"
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGON_API_KEY}", chain = "polygon" }
